version: '3.8'

services:
  scada-web:
    build: .
    container_name: aguas_del_valle_ctf
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PLC_HOST=10.10.30.100
      - DB_TYPE=mysql
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=scada_user
      - MYSQL_PASSWORD=scada_pass
      - MYSQL_DB=aguas_del_valle
      - FLASK_ENV=production
    volumes:
      - ctf_uploads:/app/uploads

  db:
    image: mysql:8.0
    container_name: aguas_del_valle_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=zacky5023
      - MYSQL_DATABASE=aguas_del_valle
      - MYSQL_USER=scada_user
      - MYSQL_PASSWORD=scada_pass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ctf_uploads:
  mysql_data:
